package model.eo;

import java.math.BigDecimal;

import model.common.ModelUtil;

import oracle.jbo.AttributeList;
import oracle.jbo.Key;
import oracle.jbo.RowIterator;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Nov 22 01:13:33 CST 2020
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ArticuloImpl
  extends EntityImpl
{
  /**
   * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
   */
  protected enum AttributesEnum
  {
    ArticuloId,
    Serial,
    Articulo,
    MarcaEquipo,
    ModeloEquipo,
    DescripcionArticulo,
    Inventario,
    OfertaProveedorArticulo,
    RequisionCompra;
    private static AttributesEnum[] vals = null;
    private static final int firstIndex = 0;

    protected int index()
    {
      return AttributesEnum.firstIndex() + ordinal();
    }

    protected static final int firstIndex()
    {
      return firstIndex;
    }

    protected static int count()
    {
      return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
    }

    protected static final AttributesEnum[] staticValues()
    {
      if (vals == null)
      {
        vals = AttributesEnum.values();
      }
      return vals;
    }
  }
  public static final int ARTICULOID = AttributesEnum.ArticuloId.index();
  public static final int SERIAL = AttributesEnum.Serial.index();
  public static final int ARTICULO = AttributesEnum.Articulo.index();
  public static final int MARCAEQUIPO = AttributesEnum.MarcaEquipo.index();
  public static final int MODELOEQUIPO = AttributesEnum.ModeloEquipo.index();
  public static final int DESCRIPCIONARTICULO = AttributesEnum.DescripcionArticulo.index();
  public static final int INVENTARIO = AttributesEnum.Inventario.index();
  public static final int OFERTAPROVEEDORARTICULO = AttributesEnum.OfertaProveedorArticulo.index();
  public static final int REQUISIONCOMPRA = AttributesEnum.RequisionCompra.index();

  /**
   * This is the default constructor (do not remove).
   */
  public ArticuloImpl()
  {
  }

  /**
   * Gets the attribute value for ArticuloId, using the alias name ArticuloId.
   * @return the value of ArticuloId
   */
  public BigDecimal getArticuloId()
  {
    return (BigDecimal) getAttributeInternal(ARTICULOID);
  }

  /**
   * Sets <code>value</code> as the attribute value for ArticuloId.
   * @param value value to set the ArticuloId
   */
  public void setArticuloId(BigDecimal value)
  {
    setAttributeInternal(ARTICULOID, value);
  }

  /**
   * Gets the attribute value for Serial, using the alias name Serial.
   * @return the value of Serial
   */
  public String getSerial()
  {
    return (String) getAttributeInternal(SERIAL);
  }

  /**
   * Sets <code>value</code> as the attribute value for Serial.
   * @param value value to set the Serial
   */
  public void setSerial(String value)
  {
    setAttributeInternal(SERIAL, value);
  }

  /**
   * Gets the attribute value for Articulo, using the alias name Articulo.
   * @return the value of Articulo
   */
  public String getArticulo()
  {
    return (String) getAttributeInternal(ARTICULO);
  }

  /**
   * Sets <code>value</code> as the attribute value for Articulo.
   * @param value value to set the Articulo
   */
  public void setArticulo(String value)
  {
    setAttributeInternal(ARTICULO, value);
  }

  /**
   * Gets the attribute value for MarcaEquipo, using the alias name MarcaEquipo.
   * @return the value of MarcaEquipo
   */
  public String getMarcaEquipo()
  {
    return (String) getAttributeInternal(MARCAEQUIPO);
  }

  /**
   * Sets <code>value</code> as the attribute value for MarcaEquipo.
   * @param value value to set the MarcaEquipo
   */
  public void setMarcaEquipo(String value)
  {
    setAttributeInternal(MARCAEQUIPO, value);
  }

  /**
   * Gets the attribute value for ModeloEquipo, using the alias name ModeloEquipo.
   * @return the value of ModeloEquipo
   */
  public String getModeloEquipo()
  {
    return (String) getAttributeInternal(MODELOEQUIPO);
  }

  /**
   * Sets <code>value</code> as the attribute value for ModeloEquipo.
   * @param value value to set the ModeloEquipo
   */
  public void setModeloEquipo(String value)
  {
    setAttributeInternal(MODELOEQUIPO, value);
  }

  /**
   * Gets the attribute value for DescripcionArticulo, using the alias name DescripcionArticulo.
   * @return the value of DescripcionArticulo
   */
  public String getDescripcionArticulo()
  {
    return (String) getAttributeInternal(DESCRIPCIONARTICULO);
  }

  /**
   * Sets <code>value</code> as the attribute value for DescripcionArticulo.
   * @param value value to set the DescripcionArticulo
   */
  public void setDescripcionArticulo(String value)
  {
    setAttributeInternal(DESCRIPCIONARTICULO, value);
  }

  /**
   * @return the associated entity oracle.jbo.RowIterator.
   */
  public RowIterator getInventario()
  {
    return (RowIterator) getAttributeInternal(INVENTARIO);
  }

  /**
   * @return the associated entity oracle.jbo.RowIterator.
   */
  public RowIterator getOfertaProveedorArticulo()
  {
    return (RowIterator) getAttributeInternal(OFERTAPROVEEDORARTICULO);
  }

  /**
   * @return the associated entity oracle.jbo.RowIterator.
   */
  public RowIterator getRequisionCompra()
  {
    return (RowIterator) getAttributeInternal(REQUISIONCOMPRA);
  }

  /**
   * @param articuloId key constituent

   * @return a Key object based on given key constituents.
   */
  public static Key createPrimaryKey(BigDecimal articuloId)
  {
    return new Key(new Object[] { articuloId });
  }

  /**
   * @return the definition object for this instance class.
   */
  public static synchronized EntityDefImpl getDefinitionObject()
  {
    return EntityDefImpl.findDefObject("model.eo.Articulo");
  }

  /**
   * Add attribute defaulting logic in this method.
   * @param attributeList list of attribute names/values to initialize the row
   */
  protected void create(AttributeList attributeList)
  {
    super.create(attributeList);
    setArticuloId(ModelUtil.getSequenceNextValue(getDBTransaction()));
  }
}

