package model.eo;

import java.math.BigDecimal;

import model.common.ModelUtil;

import oracle.jbo.AttributeList;
import oracle.jbo.Key;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Nov 18 16:46:44 CST 2020
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class EmpleadoImpl extends EntityImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        IdUsuario,
        Dui,
        NombreEmp,
        ApellidoEmp,
        TelefonoEm,
        Edad,
        Genero,
        EstadoCivil,
        DepartamentoId,
        DireccionId,
        UsuarioId,
        Departamento,
        Direccion,
        Usuario;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }
    public static final int IDUSUARIO = AttributesEnum.IdUsuario.index();
    public static final int DUI = AttributesEnum.Dui.index();
    public static final int NOMBREEMP = AttributesEnum.NombreEmp.index();
    public static final int APELLIDOEMP = AttributesEnum.ApellidoEmp.index();
    public static final int TELEFONOEM = AttributesEnum.TelefonoEm.index();
    public static final int EDAD = AttributesEnum.Edad.index();
    public static final int GENERO = AttributesEnum.Genero.index();
    public static final int ESTADOCIVIL = AttributesEnum.EstadoCivil.index();
    public static final int DEPARTAMENTOID = AttributesEnum.DepartamentoId.index();
    public static final int DIRECCIONID = AttributesEnum.DireccionId.index();
    public static final int USUARIOID = AttributesEnum.UsuarioId.index();
    public static final int DEPARTAMENTO = AttributesEnum.Departamento.index();
    public static final int DIRECCION = AttributesEnum.Direccion.index();
    public static final int USUARIO = AttributesEnum.Usuario.index();

    /**
     * This is the default constructor (do not remove).
     */
    public EmpleadoImpl() {
    }

    /**
     * Gets the attribute value for IdUsuario, using the alias name IdUsuario.
     * @return the value of IdUsuario
     */
    public BigDecimal getIdUsuario() {
        return (BigDecimal) getAttributeInternal(IDUSUARIO);
    }

    /**
     * Sets <code>value</code> as the attribute value for IdUsuario.
     * @param value value to set the IdUsuario
     */
    public void setIdUsuario(BigDecimal value) {
        setAttributeInternal(IDUSUARIO, value);
    }

    /**
     * Gets the attribute value for Dui, using the alias name Dui.
     * @return the value of Dui
     */
    public String getDui() {
        return (String) getAttributeInternal(DUI);
    }

    /**
     * Sets <code>value</code> as the attribute value for Dui.
     * @param value value to set the Dui
     */
    public void setDui(String value) {
        setAttributeInternal(DUI, value);
    }

    /**
     * Gets the attribute value for NombreEmp, using the alias name NombreEmp.
     * @return the value of NombreEmp
     */
    public String getNombreEmp() {
        return (String) getAttributeInternal(NOMBREEMP);
    }

    /**
     * Sets <code>value</code> as the attribute value for NombreEmp.
     * @param value value to set the NombreEmp
     */
    public void setNombreEmp(String value) {
        setAttributeInternal(NOMBREEMP, value);
    }

    /**
     * Gets the attribute value for ApellidoEmp, using the alias name ApellidoEmp.
     * @return the value of ApellidoEmp
     */
    public String getApellidoEmp() {
        return (String) getAttributeInternal(APELLIDOEMP);
    }

    /**
     * Sets <code>value</code> as the attribute value for ApellidoEmp.
     * @param value value to set the ApellidoEmp
     */
    public void setApellidoEmp(String value) {
        setAttributeInternal(APELLIDOEMP, value);
    }

    /**
     * Gets the attribute value for TelefonoEm, using the alias name TelefonoEm.
     * @return the value of TelefonoEm
     */
    public String getTelefonoEm() {
        return (String) getAttributeInternal(TELEFONOEM);
    }

    /**
     * Sets <code>value</code> as the attribute value for TelefonoEm.
     * @param value value to set the TelefonoEm
     */
    public void setTelefonoEm(String value) {
        setAttributeInternal(TELEFONOEM, value);
    }

    /**
     * Gets the attribute value for Edad, using the alias name Edad.
     * @return the value of Edad
     */
    public BigDecimal getEdad() {
        return (BigDecimal) getAttributeInternal(EDAD);
    }

    /**
     * Sets <code>value</code> as the attribute value for Edad.
     * @param value value to set the Edad
     */
    public void setEdad(BigDecimal value) {
        setAttributeInternal(EDAD, value);
    }

    /**
     * Gets the attribute value for Genero, using the alias name Genero.
     * @return the value of Genero
     */
    public String getGenero() {
        return (String) getAttributeInternal(GENERO);
    }

    /**
     * Sets <code>value</code> as the attribute value for Genero.
     * @param value value to set the Genero
     */
    public void setGenero(String value) {
        setAttributeInternal(GENERO, value);
    }

    /**
     * Gets the attribute value for EstadoCivil, using the alias name EstadoCivil.
     * @return the value of EstadoCivil
     */
    public String getEstadoCivil() {
        return (String) getAttributeInternal(ESTADOCIVIL);
    }

    /**
     * Sets <code>value</code> as the attribute value for EstadoCivil.
     * @param value value to set the EstadoCivil
     */
    public void setEstadoCivil(String value) {
        setAttributeInternal(ESTADOCIVIL, value);
    }

    /**
     * Gets the attribute value for DepartamentoId, using the alias name DepartamentoId.
     * @return the value of DepartamentoId
     */
    public BigDecimal getDepartamentoId() {
        return (BigDecimal) getAttributeInternal(DEPARTAMENTOID);
    }

    /**
     * Sets <code>value</code> as the attribute value for DepartamentoId.
     * @param value value to set the DepartamentoId
     */
    public void setDepartamentoId(BigDecimal value) {
        setAttributeInternal(DEPARTAMENTOID, value);
    }

    /**
     * Gets the attribute value for DireccionId, using the alias name DireccionId.
     * @return the value of DireccionId
     */
    public BigDecimal getDireccionId() {
        return (BigDecimal) getAttributeInternal(DIRECCIONID);
    }

    /**
     * Sets <code>value</code> as the attribute value for DireccionId.
     * @param value value to set the DireccionId
     */
    public void setDireccionId(BigDecimal value) {
        setAttributeInternal(DIRECCIONID, value);
    }

    /**
     * Gets the attribute value for UsuarioId, using the alias name UsuarioId.
     * @return the value of UsuarioId
     */
    public BigDecimal getUsuarioId() {
        return (BigDecimal) getAttributeInternal(USUARIOID);
    }

    /**
     * Sets <code>value</code> as the attribute value for UsuarioId.
     * @param value value to set the UsuarioId
     */
    public void setUsuarioId(BigDecimal value) {
        setAttributeInternal(USUARIOID, value);
    }

    /**
     * @return the associated entity oracle.jbo.server.EntityImpl.
     */
    public EntityImpl getDepartamento() {
        return (EntityImpl) getAttributeInternal(DEPARTAMENTO);
    }

    /**
     * Sets <code>value</code> as the associated entity oracle.jbo.server.EntityImpl.
     */
    public void setDepartamento(EntityImpl value) {
        setAttributeInternal(DEPARTAMENTO, value);
    }

    /**
     * @return the associated entity oracle.jbo.server.EntityImpl.
     */
    public EntityImpl getDireccion() {
        return (EntityImpl) getAttributeInternal(DIRECCION);
    }

    /**
     * Sets <code>value</code> as the associated entity oracle.jbo.server.EntityImpl.
     */
    public void setDireccion(EntityImpl value) {
        setAttributeInternal(DIRECCION, value);
    }

    /**
     * @return the associated entity oracle.jbo.server.EntityImpl.
     */
    public EntityImpl getUsuario() {
        return (EntityImpl) getAttributeInternal(USUARIO);
    }

    /**
     * Sets <code>value</code> as the associated entity oracle.jbo.server.EntityImpl.
     */
    public void setUsuario(EntityImpl value) {
        setAttributeInternal(USUARIO, value);
    }

    /**
     * @param idUsuario key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(BigDecimal idUsuario) {
        return new Key(new Object[] { idUsuario });
    }

    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        return EntityDefImpl.findDefObject("model.eo.Empleado");
    }

    /**
     * Add attribute defaulting logic in this method.
     * @param attributeList list of attribute names/values to initialize the row
     */
    protected void create(AttributeList attributeList) {
        super.create(attributeList);
        setIdUsuario(ModelUtil.getSequenceNextVal(getDBTransaction()));
        setGenero("F");
    }
}

